// we group our routes as auth and pages to implement the concept of multiple root layouts now auth group layouts have only footer and pages group layout have both Navbar and footer 

import Footer from "@/components/common/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
